title: "Roman List"
description: "Things I'm working on"
theme: jekyll-theme-cayman

author: "Roman List"
url: "https://wolfromanlist.github.io"

# Display markdown pages automatically
collections:
  posts:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Add navigation links
navbar-links:
  About: "/about"
  Projects: "/projects"
  Blog: "/"

google_site_verification: "kZmSJd4aqcmgCZq2DrygW2HPH099owKR3eC1lN-JmXk"

plugins:
  - jekyll-sitemap
