title: "Roman List"
description: "Things I'm working on"
theme: jekyll-theme-cayman

author: "Roman List"
url: "https://wolfromanlist.github.io"

# Display markdown pages automatically
collections:
  posts:
    output: true

# Build settings
markdown: kramdown

# Add navigation links
navbar-links:
  About: "/about"
  Projects: "/projects"
  Blog: "/"
